#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $DIR

ln -s ~/.dotfiles/.bash_profile ~/
# ln -s ~/.dotfiles/.tmux
ln -s ~/.dotfiles/.zshrc ~/

git clone git@github.com:zk/prelude.git ~/.emacs.d

# Install oh-my-zsh
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

# Install pygmentize for colorzation of source files at the shell
sudo easy_install Pygments

popd
