#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $DIR

ln -s ~/.dotfiles/.bash_profile ~/
ln -s ~/.dotfiles/.zshrc ~/
ln -s ~/.dotfiles/.tmux.conf ~/

git clone git@github.com:zk/prelude.git ~/.emacs.d

# Install oh-my-zsh
curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

# Install pygmentize for colorzation of source files at the shell
sudo easy_install Pygments

# Tmux
echo "Don't forget to install https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/"

popd
